Add min/max temperature watch face
joeycastillo/Sensor-Watch pull request #335
Opened 2023-11-28 15:20 UTC by MarkBlyth

The new face is similar to the temperature logging face, only instead it measures the temperature once a minute, and records the high and low for that hour. Only the highest and lowest temperatures from the last 24h are displayed on the screen, creating a nice simple temperature-range interface.

2023-12-01 22:14 UTC, WesleyAC commented on movement/watch_faces/sensor/minmax_face.c
> + * Copyright (c) 2023 <#author_name#>
Please fill in your name here :)

2023-12-01 22:14 UTC, WesleyAC commented on movement/watch_faces/sensor/minmax_face.h
> + * Copyright (c) 2023 <#author_name#>
Fill out name

2023-12-01 22:22 UTC, WesleyAC requested changes
Looks good overall, just a couple small things! Have you tested this on hardware?

2023-12-01 22:22 UTC, WesleyAC commented on movement/watch_faces/sensor/minmax_face.h
> + * To use...
Could you add some info on how to use the face here?

2023-12-11 11:20 UTC, MarkBlyth commented
> Looks good overall, just a couple small things! Have you tested this on hardware?

Yes, tested on Sensor-Watch lite (red).

2023-12-15 13:49 UTC, MarkBlyth commented
Changes completed, thanks!

2024-09-18 01:54 UTC, merged