Countdown autorepeat
joeycastillo/Sensor-Watch pull request #444
Opened 2024-08-25 07:22 UTC by jpdbryant

Add an "autorepeat" mode to the Countdown face.

On the countdown setting face, hold "alarm" to toggle autorepeat. When the countdown is set to autorepeat, it will automatically restart when it reaches zero. Useful to e.g. remind you to check on something every twenty minutes.

Changed to use the newer movement_schedule_background_task_for_face method, since we potentially need to schedule the new alarm when the Countdown face is not itself active.

Changed the use of indicators within the Countdown face. Formerly, the "bell" indicator was used to indicate an active countdown. Now, we use the "signal" indicator for this, and the "bell" indicates autorepeat mode. This seems more consistent with those icons' traditional purpose - the "bell" indicates a repeating alarm, the "signal" indicates a one-off.

2024-09-03 19:15 UTC, matheusmoreira requested changes
The following commits have already been merged separately and are already in main:

 - 20b4a32835d6b8aedda40cb49025cf3fb78beebe
 - dcd4d12c0ab55aea50fc93f4de390a815d4ff6f5
 - e2c5babb2c7cd0141a5a78e9f94458804bbd9764

The following merge commit is also unnecessary:

 - 10ccab9ce3d35e2806c0111c3f833d8606713793

Please rebase the following commit on top of the latest `main` and then force push your branch:

 - 6847619e39b8aafcd96f609dd6c32b8846aacf57

If `main` moves forward after you have submitted a pull request, please do not merge `main` into your branch. Always rebase your changes on top of the latest `main` instead.

```shell
# change current branch to your branch
git checkout your-branch
# rebase commits from current branch on top of main
git rebase main
```

2024-09-03 19:37 UTC, jpdbryant commented
Sorry for my terrible pull requests! As you can see I am new to github workflow. I will look at this again in a few days. Thanks for taking the time to untangle what's actually required.

2024-09-03 19:53 UTC, matheusmoreira commented
It's not terrible at all, it's actually pretty great! I read the code and it seems fine for inclusion and testing. This is a very useful feature and I expect the changes to go straight into `next` as soon as the requested rebasing is implemented.

This is just to improve the quality of the commit log, and also to make the PR automatically close when `next` is merged into `main`. Don't worry about being new or inexperienced. If I need something in order to merge, I'll politely request it here and provide help if needed.

Thank you for your contribution!

2024-09-07 19:53 UTC, matheusmoreira approved these changes

2024-09-08 23:00 UTC, matheusmoreira commented
Hello! This is not gonna be a blocker or anything, the PR is already in `next`. I'd like to ask you though: is the time zone code strictly necessary? We might have found a way to simplify it by keeping all logic in the native timezone. What do you think?

2024-09-09 05:17 UTC, jpdbryant commented
I didn't touch any of the timezone code for this change, I didn't even understand it! I guess the thing to consider is - if you change the timezone while a countdown is running, it shouldn't affect the countdown.

2024-09-10 08:24 UTC, voloved commented
@matheusmoreira 
I added this commit for removing timezones: https://github.com/joeycastillo/Sensor-Watch/pull/473

2024-09-17 20:51 UTC, matheusmoreira commented
This PR has been merged into `main` but did not automatically close because it was rebased.

2024-09-17 20:51 UTC, closed without merging